import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Alert,
  Dimensions,
  Share,
} from 'react-native';
import { useApp } from '../context/AppContext';
import { GameMetrics, MLFeatures, MLPrediction } from '../types';
import { COLORS, FONTS, SPACING, ML_THRESHOLDS } from '../constants';
import { apiService } from '../services/api';

const { width } = Dimensions.get('window');

interface ResultScreenProps {
  navigation: any;
  route: any;
}

const ResultScreen: React.FC<ResultScreenProps> = ({ navigation, route }) => {
  const { sessionData, metrics, features } = route.params;
  const { currentLanguage } = useApp();
  const [prediction, setPrediction] = useState<MLPrediction | null>(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    // Simulate ML prediction (replace with actual API call)
    simulateMLPrediction();
  }, []);

  const simulateMLPrediction = () => {
    // Simulate ML prediction based on features
    const riskScore = calculateRiskScore(features);
    const riskLevel = getRiskLevel(riskScore);
    
    const mockPrediction: MLPrediction = {
      riskLevel,
      confidence: Math.random() * 0.3 + 0.7, // 70-100% confidence
      features,
      timestamp: new Date(),
    };
    
    setPrediction(mockPrediction);
  };

  const calculateRiskScore = (features: MLFeatures): number => {
    // Simple risk calculation based on features
    let score = 0;
    
    // Higher reaction time increases risk
    if (features.mean_rt > 2000) score += 0.3;
    else if (features.mean_rt > 1500) score += 0.2;
    else if (features.mean_rt > 1000) score += 0.1;
    
    // Lower accuracy increases risk
    if (features.accuracy < 60) score += 0.4;
    else if (features.accuracy < 80) score += 0.2;
    else if (features.accuracy < 90) score += 0.1;
    
    // Higher switch cost increases risk
    if (features.switch_cost > 500) score += 0.2;
    else if (features.switch_cost > 300) score += 0.1;
    
    // Higher error rates increase risk
    score += (features.perseverative_error_rate / 100) * 0.2;
    score += (features.inhibition_error_rate / 100) * 0.2;
    
    return Math.min(score, 1);
  };

  const getRiskLevel = (score: number): 'low' | 'moderate' | 'high' => {
    if (score <= 0.33) return 'low';
    if (score <= 0.66) return 'moderate';
    return 'high';
  };

  const handleShare = async () => {
    try {
      const message = `Assessment Results:\n\n` +
        `Accuracy: ${metrics.accuracy.toFixed(1)}%\n` +
        `Mean Reaction Time: ${metrics.meanReactionTime.toFixed(0)}ms\n` +
        `Switch Cost: ${metrics.switchCost.toFixed(0)}ms\n` +
        `Risk Level: ${prediction?.riskLevel.toUpperCase()}\n\n` +
        `Generated by Autism Screening App`;
      
      await Share.share({
        message,
        title: 'Assessment Results',
      });
    } catch (error) {
      console.error('Failed to share results:', error);
    }
  };

  const handleSaveReport = () => {
    Alert.alert(
      'Save Report',
      'Report will be saved to the child\'s profile and can be accessed from the dashboard.',
      [
        { text: 'Cancel', style: 'cancel' },
        { text: 'Save', onPress: () => {
          // TODO: Implement report saving
          Alert.alert('Success', 'Report saved successfully');
        }},
      ]
    );
  };

  const handleNewAssessment = () => {
    navigation.navigate('MainDashboard');
  };

  const MetricCard = ({ title, value, unit, color, icon }: any) => (
    <View style={[styles.metricCard, { borderLeftColor: color }]}>
      <Text style={styles.metricIcon}>{icon}</Text>
      <View style={styles.metricContent}>
        <Text style={styles.metricValue}>{value}{unit}</Text>
        <Text style={styles.metricTitle}>{title}</Text>
      </View>
    </View>
  );

  const RiskIndicator = ({ riskLevel, confidence }: any) => {
    const riskData = ML_THRESHOLDS[riskLevel];
    
    return (
      <View style={styles.riskContainer}>
        <View style={[styles.riskIndicator, { backgroundColor: riskData.color }]}>
          <Text style={styles.riskLevelText}>{riskData.label}</Text>
          <Text style={styles.riskConfidence}>
            Confidence: {(confidence * 100).toFixed(0)}%
          </Text>
        </View>
        <Text style={styles.riskDescription}>
          {riskLevel === 'low' 
            ? 'The child shows typical cognitive flexibility patterns.'
            : riskLevel === 'moderate'
            ? 'The child shows some difficulties with cognitive flexibility. Further assessment may be beneficial.'
            : 'The child shows significant difficulties with cognitive flexibility. Professional evaluation is recommended.'
          }
        </Text>
      </View>
    );
  };

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()}>
          <Text style={styles.backButton}>‹ Back</Text>
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Assessment Results</Text>
        <TouchableOpacity onPress={handleShare}>
          <Text style={styles.shareButton}>Share</Text>
        </TouchableOpacity>
      </View>

      <ScrollView style={styles.content} showsVerticalScrollIndicator={false}>
        {/* Risk Level Section */}
        {prediction && (
          <View style={styles.riskSection}>
            <Text style={styles.sectionTitle}>Risk Assessment</Text>
            <RiskIndicator 
              riskLevel={prediction.riskLevel} 
              confidence={prediction.confidence} 
            />
          </View>
        )}

        {/* Performance Metrics */}
        <View style={styles.metricsSection}>
          <Text style={styles.sectionTitle}>Performance Metrics</Text>
          <View style={styles.metricsGrid}>
            <MetricCard
              title="Accuracy"
              value={metrics.accuracy.toFixed(1)}
              unit="%"
              color={COLORS.success}
              icon="🎯"
            />
            <MetricCard
              title="Mean RT"
              value={metrics.meanReactionTime.toFixed(0)}
              unit="ms"
              color={COLORS.primary}
              icon="⏱️"
            />
            <MetricCard
              title="Switch Cost"
              value={metrics.switchCost.toFixed(0)}
              unit="ms"
              color={COLORS.warning}
              icon="🔄"
            />
            <MetricCard
              title="Errors"
              value={metrics.perseverativeErrors + metrics.inhibitionErrors}
              unit=""
              color={COLORS.error}
              icon="❌"
            />
          </View>
        </View>

        {/* Detailed Analysis */}
        <View style={styles.analysisSection}>
          <Text style={styles.sectionTitle}>Detailed Analysis</Text>
          
          <View style={styles.analysisCard}>
            <Text style={styles.analysisTitle}>Cognitive Flexibility</Text>
            <Text style={styles.analysisText}>
              The child completed {metrics.totalTrials} trials with {metrics.accuracy.toFixed(1)}% accuracy.
              {metrics.switchCost > 300 
                ? ' The switch cost is elevated, indicating difficulty adapting to rule changes.'
                : ' The switch cost is within normal range, indicating good cognitive flexibility.'
              }
            </Text>
          </View>

          <View style={styles.analysisCard}>
            <Text style={styles.analysisTitle}>Error Patterns</Text>
            <Text style={styles.analysisText}>
              {metrics.perseverativeErrors > 0 
                ? `The child made ${metrics.perseverativeErrors} perseverative errors, suggesting difficulty inhibiting previous responses.`
                : 'No perseverative errors were observed, indicating good response inhibition.'
              }
              {metrics.inhibitionErrors > 0 
                ? ` Additionally, ${metrics.inhibitionErrors} inhibition errors were recorded.`
                : ''
              }
            </Text>
          </View>

          <View style={styles.analysisCard}>
            <Text style={styles.analysisTitle}>Recovery Time</Text>
            <Text style={styles.analysisText}>
              {metrics.recoveryTrials === 0 
                ? 'The child showed immediate adaptation to rule changes.'
                : `The child required ${metrics.recoveryTrials} trials to recover after the rule switch.`
              }
            </Text>
          </View>
        </View>

        {/* Recommendations */}
        <View style={styles.recommendationsSection}>
          <Text style={styles.sectionTitle}>Recommendations</Text>
          
          <View style={styles.recommendationsList}>
            {prediction?.riskLevel === 'low' && (
              <>
                <Text style={styles.recommendationItem}>
                  • Continue monitoring cognitive development
                </Text>
                <Text style={styles.recommendationItem}>
                  • Encourage activities that promote executive functioning
                </Text>
                <Text style={styles.recommendationItem}>
                  • Regular follow-up assessments recommended
                </Text>
              </>
            )}
            
            {prediction?.riskLevel === 'moderate' && (
              <>
                <Text style={styles.recommendationItem}>
                  • Consider additional assessment tools
                </Text>
                <Text style={styles.recommendationItem}>
                  • Implement targeted cognitive training exercises
                </Text>
                <Text style={styles.recommendationItem}>
                  • Schedule follow-up assessment in 3-6 months
                </Text>
                <Text style={styles.recommendationItem}>
                  • Consider consultation with developmental specialist
                </Text>
              </>
            )}
            
            {prediction?.riskLevel === 'high' && (
              <>
                <Text style={styles.recommendationItem}>
                  • Immediate referral to developmental specialist recommended
                </Text>
                <Text style={styles.recommendationItem}>
                  • Comprehensive developmental assessment needed
                </Text>
                <Text style={styles.recommendationItem}>
                  • Consider early intervention services
                </Text>
                <Text style={styles.recommendationItem}>
                  • Regular monitoring and support essential
                </Text>
              </>
            )}
          </View>
        </View>
      </ScrollView>

      <View style={styles.footer}>
        <TouchableOpacity style={styles.secondaryButton} onPress={handleSaveReport}>
          <Text style={styles.secondaryButtonText}>Save Report</Text>
        </TouchableOpacity>
        <TouchableOpacity style={styles.primaryButton} onPress={handleNewAssessment}>
          <Text style={styles.primaryButtonText}>New Assessment</Text>
        </TouchableOpacity>
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: SPACING.lg,
    paddingTop: SPACING.lg,
    paddingBottom: SPACING.md,
    backgroundColor: COLORS.surface,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  backButton: {
    fontSize: FONTS.sizes.lg,
    color: COLORS.primary,
    fontWeight: '600',
  },
  headerTitle: {
    fontSize: FONTS.sizes.lg,
    fontWeight: 'bold',
    color: COLORS.text,
  },
  shareButton: {
    fontSize: FONTS.sizes.md,
    color: COLORS.primary,
    fontWeight: '600',
  },
  content: {
    flex: 1,
    paddingHorizontal: SPACING.lg,
  },
  sectionTitle: {
    fontSize: FONTS.sizes.lg,
    fontWeight: 'bold',
    color: COLORS.text,
    marginBottom: SPACING.md,
    marginTop: SPACING.lg,
  },
  riskSection: {
    marginTop: SPACING.lg,
  },
  riskContainer: {
    backgroundColor: COLORS.surface,
    borderRadius: 12,
    padding: SPACING.lg,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  riskIndicator: {
    padding: SPACING.lg,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: SPACING.md,
  },
  riskLevelText: {
    fontSize: FONTS.sizes.xl,
    fontWeight: 'bold',
    color: COLORS.surface,
    marginBottom: SPACING.xs,
  },
  riskConfidence: {
    fontSize: FONTS.sizes.sm,
    color: COLORS.surface,
    opacity: 0.9,
  },
  riskDescription: {
    fontSize: FONTS.sizes.md,
    color: COLORS.textSecondary,
    lineHeight: 22,
  },
  metricsSection: {
    marginTop: SPACING.lg,
  },
  metricsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  metricCard: {
    width: (width - SPACING.lg * 2 - SPACING.md) / 2,
    backgroundColor: COLORS.surface,
    borderRadius: 12,
    padding: SPACING.md,
    marginBottom: SPACING.md,
    borderLeftWidth: 4,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  metricIcon: {
    fontSize: 24,
    marginRight: SPACING.sm,
  },
  metricContent: {
    flex: 1,
  },
  metricValue: {
    fontSize: FONTS.sizes.xl,
    fontWeight: 'bold',
    color: COLORS.text,
  },
  metricTitle: {
    fontSize: FONTS.sizes.sm,
    color: COLORS.textSecondary,
  },
  analysisSection: {
    marginTop: SPACING.lg,
  },
  analysisCard: {
    backgroundColor: COLORS.surface,
    borderRadius: 12,
    padding: SPACING.lg,
    marginBottom: SPACING.md,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  analysisTitle: {
    fontSize: FONTS.sizes.md,
    fontWeight: '600',
    color: COLORS.text,
    marginBottom: SPACING.sm,
  },
  analysisText: {
    fontSize: FONTS.sizes.sm,
    color: COLORS.textSecondary,
    lineHeight: 20,
  },
  recommendationsSection: {
    marginTop: SPACING.lg,
    marginBottom: SPACING.xl,
  },
  recommendationsList: {
    backgroundColor: COLORS.surface,
    borderRadius: 12,
    padding: SPACING.lg,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  recommendationItem: {
    fontSize: FONTS.sizes.sm,
    color: COLORS.text,
    lineHeight: 22,
    marginBottom: SPACING.sm,
  },
  footer: {
    flexDirection: 'row',
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.lg,
    backgroundColor: COLORS.surface,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    gap: SPACING.md,
  },
  primaryButton: {
    flex: 1,
    backgroundColor: COLORS.primary,
    borderRadius: 8,
    paddingVertical: SPACING.md,
    alignItems: 'center',
  },
  primaryButtonText: {
    color: COLORS.surface,
    fontSize: FONTS.sizes.md,
    fontWeight: '600',
  },
  secondaryButton: {
    flex: 1,
    backgroundColor: COLORS.background,
    borderRadius: 8,
    paddingVertical: SPACING.md,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  secondaryButtonText: {
    color: COLORS.text,
    fontSize: FONTS.sizes.md,
    fontWeight: '600',
  },
});

export default ResultScreen;
